# Generated by Django 2.1.7 on 2019-11-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sonido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('duracion', models.PositiveIntegerField(default=1)),
                ('sonido', models.FileField(blank=True, default='', upload_to='media')),
            ],
        ),
    ]
