# Generated by Django 2.0.7 on 2019-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.PositiveIntegerField()),
                ('className', models.CharField(max_length=200)),
                ('audioFile', models.FileField(default='', upload_to='media/audios')),
                ('audioParameters', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='sonido',
            name='sonido',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
