# Generated by Django 2.0.7 on 2019-11-19 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraid', '0003_auto_20191118_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
