# Generated by Django 2.0.7 on 2019-11-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraid', '0006_alert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.CharField(max_length=200),
        ),
    ]
