# Generated by Django 2.0.7 on 2019-11-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraid', '0007_auto_20191119_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alertMessage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
