# Generated by Django 2.0.7 on 2019-11-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraid', '0008_auto_20191120_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audioFile',
            field=models.CharField(max_length=500),
        ),
    ]
