# Generated by Django 2.0.7 on 2019-11-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraid', '0009_auto_20191120_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='audioParameters',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endDate',
        ),
        migrations.AddField(
            model_name='event',
            name='accumulated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
