# Generated by Django 2.0.7 on 2019-11-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraid', '0010_auto_20191120_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sonido',
        ),
        migrations.AddField(
            model_name='alert',
            name='events',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
